In [1]:

import streamlit as st
from streamlit_option_menu import option_menu
import yfinance as yf
from datetime import date, datetime, timedelta
import matplotlib.pyplot as plt
import pandas as pd
import pandas_datareader.data as web
import plotly.graph_objs as go
import os

# Seu código aqui

In [2]:
# FALTA FAZER

# o valor que paguei foi x
# o valor máximo foi x em data tal
# mes com maior volume negociado, volume e média diária
# o mês com melhor mediana foi tal, mediana tal
# o mês com pior mediana foi tal, mediana tal
# se vale mostrar valor do minério
# se petrobras mostrar valor do petroleo
# média móvel com setinha para 1 mes
# média móvel com setinha para 3 meses


# Tabela com meus tickers
# Quando teve a maior média móvel nos últimos cinco anos
# # Quando teve a menor média móvel nos últimos cinco anos
# qual ação minha que está dando mais lucro hoje
# qual ação minha que está dando mais preju hoje

In [7]:


import yfinance as yf
from datetime import date, datetime, timedelta
import os
import pandas as pd
import plotly.graph_objs as go
import streamlit as st
from streamlit_option_menu import option_menu
import yfinance as yf

# importei depois
from datetime import datetime, timedelta
import pandas_datareader.data as web
import matplotlib.pyplot as plt

# from fbprophet import Prophet
# from fbprophet.plot import plot_plotly, plot_components_plotly
from plotly import graph_objs as go



# codigo do dashboard
DATA_INICIO = "2015-01-05"
DATA_FIM = date.today().strftime("%Y-%m-%d")
st.title("Minhas ações")


def pegar_dados_acoes(arquivo,sep):
    # path = "\\wsl.localhost\Ubuntu\home\gutao\dev\streamlit_docker\acoes\acoes.csv"
    path = "dados/" + arquivo
    return pd.read_csv(path, delimiter=sep)


df_tickers = pegar_dados_acoes("tickers.csv",";")
tickers = df_tickers["ticker"].tolist()

In [8]:
df_tickers

     ticker  quantidade paguei   investi       data atualizado_cdi_300424
0  RAIL3.SA          57   1,55   1590,00   1/1/2021               2182,00
1  B3SA3.SA        1000  11,80  11800,00  14/5/2015              25557,00
2  CSUD3.SA        3000   8,60  25800,00  14/5/2015              55879,00
3  CMIG4.SA        1418  28,50  40413,00  14/5/2015              87529,00
4  ENBR3.SA        1200  31,71  38052,00  14/5/2015              82415,00
5  PETR4.SA         250  37,00   9250,00  14/5/2015              20034,00
6  SHUL4.SA        1400  16,50  23100,00  14/5/2015              50031,00
7  VALE3.SA         100  46,00   4600,00  26/1/2019               6843,00

In [24]:
# ESCREVER COTACOES

# Datas de início e fim
start_date = '2015-01-01'
end_date = pd.Timestamp.today().strftime('%Y-%m-%d')

# Dicionário para armazenar os DataFrames de cotações
quotes = {}

# Pegar csv cotacoes
df_cotacoes = pegar_dados_acoes("cotacoes.csv",",")

# Se precisar carregar todos os tickers novamente descomentar e executar este código

In [25]:
'''
# Baixar cotações para cada ticker na lista
for ticker in tickers:
    data = yf.download(ticker, start=start_date, end=end_date)
    quotes[ticker] = data

# Concatenar os DataFrames em um DataFrame único
df_cotacoes = pd.concat(quotes.values(), keys=quotes.keys(), names=['Ticker', 'Date'])

# Resetar o índice
df_cotacoes.reset_index(inplace=True)

# Salvar em um arquivo CSV
df_cotacoes.to_csv('dados/cotacoes.csv', index=False)

# Verificar o DataFrame
print(df_cotacoes.tail())'''

"\n# Baixar cotações para cada ticker na lista\nfor ticker in tickers:\n    data = yf.download(ticker, start=start_date, end=end_date)\n    quotes[ticker] = data\n\n# Concatenar os DataFrames em um DataFrame único\ndf_cotacoes = pd.concat(quotes.values(), keys=quotes.keys(), names=['Ticker', 'Date'])\n\n# Resetar o índice\ndf_cotacoes.reset_index(inplace=True)\n\n# Salvar em um arquivo CSV\ndf_cotacoes.to_csv('dados/cotacoes.csv', index=False)\n\n# Verificar o DataFrame\nprint(df_cotacoes.tail())"

In [10]:
df_cotacoes.head()

,Ticker,Date,Open,High,Low,Close,Adj Close,Volume
0,RAIL3.SA,2015-04-02,13.800000,17.200001,13.8,17.200001,17.043989,2668180.0
1,RAIL3.SA,2015-04-06,17.600000,18.500000,17.1,17.400000,17.242172,1519710.0
2,RAIL3.SA,2015-04-07,16.799999,16.900000,15.6,15.800000,15.656686,2354260.0
3,RAIL3.SA,2015-04-08,16.100000,16.200001,15.5,15.600000,15.458500,1826330.0
4,RAIL3.SA,2015-04-09,15.400000,16.900000,15.3,16.299999,16.152149,2230390.0

In [11]:
import yfinance as yf
import pandas as pd
import os

## Append no csv caso esteja defasado em relação a data atual

In [26]:
# Converter a coluna 'Date' para o formato de data
df_cotacoes['Date'] = pd.to_datetime(df_cotacoes['Date'])

datamax = df_cotacoes['Date'].max()
datamax

Timestamp('2024-05-06 00:00:00')

In [27]:

# Variável para rastrear se encontramos cotações após a data máxima
encontrou_cotacoes = False

# Verificar se existe cotação para uma data maior do que datamax para os tickers da lista
for ticker in tickers:
    # Baixar cotações para o ticker
    data = yf.download(ticker, start=(datamax + pd.Timedelta(days=1)), end=pd.Timestamp.today())
    # Se houver dados e a data máxima for menor do que a data mais recente dos dados, exibir as cotações
    if not data.empty and data.index.max() > datamax:
        encontrou_cotacoes = True
        print(f"Existe cotação para o ticker {ticker} após a data máxima:")
        print(data)
        encontrou = True

# Se não encontrou cotações após a data máxima, imprimir mensagem
if not encontrou_cotacoes:
    print("Não foram encontradas cotações após a data máxima para os tickers fornecidos.")
    encontrou = False

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- ENBR3.SA: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
Não foram encontradas cotações após a data máxima para os tickers fornecidos.

In [28]:
#encontrou = True

In [29]:
if encontrou:
    for ticker in tickers:
        data = yf.download(ticker, start=datamax, end=datetime.today().strftime('%Y-%m-%d'))
        data['Ticker'] = ticker  # Adicionar coluna com o ticker para identificação
        df_cotacoes = pd.concat([df_cotacoes, data], ignore_index=False)

In [22]:
df_cotacoes.tail()

,Ticker,Date,Open,High,Low,Close,Adj Close,Volume
2024-05-06 00:00:00,CSUD3.SA,NaT,18.370001,18.549999,18.020000,18.02,18.02,59700.0
2024-05-06 00:00:00,CMIG4.SA,NaT,10.520000,10.630000,10.430000,10.43,10.43,12790100.0
2024-05-06 00:00:00,PETR4.SA,NaT,39.869999,40.360001,39.720001,40.16,40.16,22977200.0
2024-05-06 00:00:00,SHUL4.SA,NaT,6.220000,6.260000,6.160000,6.16,6.16,377500.0
2024-05-06 00:00:00,VALE3.SA,NaT,64.220001,64.699997,63.950001,64.18,64.18,13423600.0